### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by slschnorr** [snayfach/MicrobeCensus#19] opened 2018-04-08 02:27 UTC
Hi, just installed and ran the test in the "tests" directory with the following:

`.E.
======================================================================
ERROR: test_ags_estimation (__main__.Pipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_microbe_census.py", line 21, in setUp
    self.observed = microbe_census.run_pipeline({'seqfiles':[self.infile]})[0]
  File "/usr/lib/python2.7/site-packages/microbe_census/microbe_census.py", line 583, in run_pipeline
    paths = get_relative_paths(args)
  File "/usr/lib/python2.7/site-packages/microbe_census/microbe_census.py", line 109, in get_relative_paths
    if args['rapsearch']:
KeyError: 'rapsearch'

----------------------------------------------------------------------
Ran 3 tests in 0.066s

FAILED (errors=1)`

**Comment by snayfach** [comment] 2018-04-08 23:39
I'm not sure what the problem is. I just ran the tests without any errors:

```
$ git clone https://github.com/snayfach/MicrobeCensus
$ cd MicrobeCensus
$ export PATH=$PATH:$PWD/scripts
$ export PYTHONPATH=$PYTHONPATH:$PWD
$ cd tests/
$ python test_microbe_census.py -vf
test_detect_filetype (__main__.FileType) ... ok
test_ags_estimation (__main__.Pipeline) ... ok
test_read_list (__main__.ReadList) ... ok

----------------------------------------------------------------------
Ran 3 tests in 41.532s

OK
```

**Comment by slschnorr** [comment] 2018-04-09 03:11
How strange. This time I git cloned it and then installed with the setup.py install, rather than downloading the tarball, and the test worked.

**Comment by snayfach** [comment] 2018-04-09 03:37
I just published a new release so this should be fixed now.

Thanks,
Stephen

**Closed by snayfach** 2018-04-09 03:37 UTC
